### ISSUE TITLE
change hibernate connection properties

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#2250]
**Is your feature request related to a problem? Please describe.**
Currently, the release_mode of the hibernate connection is on_close (default), which keeps the connection until the hibernate session is closed.
There is a risk of error if it does not match db timeout setting.
Also, resources are wasted due to connection.
So we need to change it to after_transaction to release it at the end of the transaction.

**Describe the solution you'd like**
add properties to application.yaml 
```
spring:
  jpa:
    properties:
      hibernate:
        connection:
          release_mode: after_transaction
```

**Describe alternatives you've considered**

**Additional context**
