### ISSUE TITLE
Apply Liquibase for Schema Management

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#2756]
**Is your feature request related to a problem? Please describe.**
Apply Liquibase to make Schema versioning explicit.

Database Schema Management Tool
https://www.liquibase.org/

# Liquibase-core
Library to update db changelog to Spring.datasource when running Application

1. Add Maven Dependency
The liquibase version should match the one managed by  https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-dependencies/${spring-boot.version}

Spring boot : 1.5.9.RELEASE
Liquibase Core : 3.5.3

metatron-discovery/discovery-server/pom.xml
```
<!-- Liquibase -->
<dependencies>
    <dependency>
        <groupId>org.liquibase</groupId>
        <artifactId>liquibase-core</artifactId>
        <version>3.5.3</version>
    </dependency>
</dependencies>
```

2. Add ChangeLogFile property to application.yaml and change Hibernate hbm2ddl property from auto to "none" or "validate".
(When using the "validate" option in H2, there is an issue in the typecheck of a field whose Type is CLOB, so set it to "none".)

application.yaml
```
liquibase:
  change-log: classpath:db/changelog/db.changelog-master.xml
 
# mysql
spring:
  profiles: mysql-default-db
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
 
# h2
spring:
  profiles: h2-default-db
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
```

3. Create a db.changelog-master.xml file in the specified path. (src/main/resources/db/changelog/db.changelog-master.xml)
Can also define attributes to use when inserting. (ex: now)

src/main/resources/db/changelog/db.changelog-master.xml
```
<databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
                      http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.1.xsd">
 
    <property name="now" value="SYSDATE" dbms="oracle" />
    <property name="now" value="NOW()" dbms="mysql" />
    <property name="now" value="NOW()" dbms="postgresql" />
    <property name="now" value="CURRENT_DATE()" dbms="h2" />
    <property name="now" value="GETDATE()" dbms="mssql" />
 
    <!-- initial changelog -->
    <include file="discovery.changelog-initial.xml" relativeToChangelogFile="true"/>
</databaseChangeLog>
```

4. Schema change history management
File that records Schema changes with Author, Id unique values
discovery.changelog-initial.xml: Default Schema ChangeSet to replace existing default.sql and hibernate ddl sql
discovery.changelog-x.x.xl.xml: Schema changes to be included in the Discovery Release

# Liquibase Maven Plugin
https://www.liquibase.org/documentation/maven/index.html
Plugin that can execute Liquibase Command using Maven. Used to create a changeLog.

1. Add Maven plugin
The configuration.properties must be configured according to the command to be executed.
metatron-discovery/pom.xml
```
<properties>
        <!-- liquibase -->
        <!-- The javassist version should match the one managed by
        https://mvnrepository.com/artifact/org.hibernate/hibernate-core/${hibernate.version} -->
        <javassist.version>3.24.0-GA</javassist.version>
        <!-- The liquibase version should match the one managed by
        https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-dependencies/${spring-boot.version} -->
        <liquibase.version>3.5.3</liquibase.version>
        <liquibase-hibernate5.version>3.6</liquibase-hibernate5.version>
        <validation-api.version>2.0.1.Final</validation-api.version>
</properties>
```

metatron-discovery/discovery-server/pom.xml
```
<plugins>
    <plugin>
        <groupId>org.liquibase</groupId>
        <artifactId>liquibase-maven-plugin</artifactId>
        <version>${liquibase.version}</version>
        <configuration>
            <systemProperties>
                <property>
                    <name>jadira.usertype.useJdbc42Apis</name>
                    <value>false</value>
                </property>
            </systemProperties>
            <propertyFile>src/main/resources/liquibase-diff-hibernate.yaml</propertyFile>
            <propertyFileWillOverride>true</propertyFileWillOverride>
            <diffChangeLogFile>src/main/resources/db/changelog/${maven.build.timestamp}_changelog.xml</diffChangeLogFile>
            <verbose>false</verbose>
            <logging>info</logging>
        </configuration>
        <dependencies>
            <dependency>
                <groupId>org.javassist</groupId>
                <artifactId>javassist</artifactId>
                <version>${javassist.version}</version>
            </dependency>
            <dependency>
                <groupId>org.liquibase.ext</groupId>
                <artifactId>liquibase-hibernate5</artifactId>
                <version>${liquibase-hibernate5.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.hibernate</groupId>
                        <artifactId>hibernate-core</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.hibernate</groupId>
                        <artifactId>hibernate-entitymanager</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.hibernate</groupId>
                        <artifactId>hibernate-envers</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-data-jpa</artifactId>
                <version>${spring.boot.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.hibernate</groupId>
                        <artifactId>hibernate-entitymanager</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.hibernate</groupId>
                        <artifactId>hibernate-core</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.hibernate</groupId>
                <artifactId>hibernate-core</artifactId>
                <version>${hibernate.version}</version>
            </dependency>
            <dependency>
                <groupId>org.hibernate</groupId>
                <artifactId>hibernate-entitymanager</artifactId>
                <version>${hibernate.version}</version>
            </dependency>
            <dependency>
                <groupId>javax.validation</groupId>
                <artifactId>validation-api</artifactId>
                <version>${validation-api.version}</version>
            </dependency>
            <dependency>
                <groupId>org.jadira.usertype</groupId>
                <artifactId>usertype.core</artifactId>
                <version>7.0.0.CR1</version>
            </dependency>
            <dependency>
                <groupId>joda-time</groupId>
                <artifactId>joda-time</artifactId>
                <version>2.9.5</version>
            </dependency>
        </dependencies>
    </plugin>
</plugins>
```

2. Generate Change Log from DB
Extract all schema information of collection target DB into ChangeLog.xml.

src/main/resources/liquibase-generate.yaml
```
liquibase:
  url: jdbc:mysql://localhost:3306/polaris_341?useUnicode=true&characterEncoding=utf8
  username: polaris
  password: polaris
  driver: com.mysql.jdbc.Driver
```
```
$ mvn liquibase:generateChangeLog
```

3. Generate Diff changeLog Between Schema1 and Schema2

src/main/resources/liquibase-diff.yaml
```
liquibase:
  changeLogFile: src/main/resources/db/changelog/db.changelog-master.xml
  diffChangeLogFile: src/main/resources/test/liquibase-341_342.xml
  url: jdbc:mysql://localhost:3306/polaris_341?useUnicode=true&characterEncoding=utf8
  username: polaris
  password: polaris
  driver: com.mysql.jdbc.Driver
  referenceUrl: jdbc:mysql://localhost:3306/polaris_342?useUnicode=true&characterEncoding=utf8
  referenceDriver: com.mysql.jdbc.Driver
  referenceUsername: polaris
  referencePassword: polaris
```
```
$ mvn liquibase:diff
```

4. Generate Diff changeLog Between DB and Hibernate Entity
src/main/resources/liquibase-diff-hibernate.yaml
```
liquibase:
  changeLogFile: src/main/resources/db/changelog/db.changelog-master.xml
  url: jdbc:mysql://localhost:3306/polaris_master?useUnicode=true&characterEncoding=utf8
  username: polaris
  password: polaris
  driver: com.mysql.jdbc.Driver
  referenceUrl: hibernate:spring:app.metatron.discovery.domain?dialect=org.hibernate.dialect.MySQL5InnoDBDialect&naming_strategy=org.hibernate.cfg.ImprovedNamingStrategy
```

```
$ mvn liquibase:diff
```

5. After creating XML, include it in changeLog
-Modify the XML so that only the contents of the entity that you have modified remain, except for the table that is automatically generated among the generated XML.
-If there is a ChangeLog of the current release version, append it to the file, and if not, modify the XML file name according to the release version (/resources/db/changelog/discovery.changelog-x.x.x.xml)
-Add the ChangeLog file added to db.changelog-master.xml

db.changelog-master.xml
```
<databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
                      http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.1.xsd">

    <property name="now" value="SYSDATE" dbms="oracle" />
    <property name="now" value="NOW()" dbms="mysql" />
    <property name="now" value="NOW()" dbms="postgresql" />
    <property name="now" value="CURRENT_DATE()" dbms="h2" />
    <property name="now" value="GETDATE()" dbms="mssql" />

    <!-- initial changelog -->
    <include file="discovery.changelog-initial.xml" relativeToChangelogFile="true"/>

    <!-- discovery release based changelog -->
    <include file="discovery.changelog-3.4.0.xml" relativeToChangelogFile="true"/>
</databaseChangeLog>
```
