### ISSUE TITLE
Configuration instructions and examples

### ISSUE THREAD

**Issue by FourSpaces** [metatron-app/metatron-discovery#2816]
I don't know how to configure it. I tried it a few times and there were various errors on the page. I want to give up.

**Comment by kyungtaak** [comment]
@FourSpaces  I'm sorry to hear that..;;; Could you tell me what the configuration is ? I think I can guide for you.

**Comment by FourSpaces** [comment]
I want to configure servier to connect to my druid cluster

**Comment by kyungtaak** [comment]
@FourSpaces ok. See the section below in the link: https://github.com/metatron-app/metatron-discovery/blob/master/discovery-server/src/main/asciidoc/application-config-guide.adoc

```
polaris:
  engine:
    # Specify representative access url by engine node, application requires only 3 nodes
    hostname:
      broker: http://localhost:8082
      overlord: http://localhost:8090
      coordinator: http://localhost:8081
    ingestion:
      # Used when forwarding files from an application to an engine cluster when loading local files
      loader:
        remoteType: SSH # "LOCAL" is the default value, but if the engine is configured as a separate cluster, use "SSH" mode for remote communication.
        localBaseDir: ${java.io.tmpdir:-/tmp}
        remoteDir: ${java.io.tmpdir:-/tmp}
        # Specifies the host information where the middle manager node is located.
        hosts:
          middlemanager01: # It must be the hostname recognized by the engine. Refer to the worker hostname on the engine console.
            port: 22
            username: metatron
            password: pem:${METATRON_HOME}/pem/user-metatron.pem # Specify "pem" prefix and pem file location if you use pem file when connecting to remote host
          "[middlemanager.01]": # If the host name contains "." If included, display like this
            port: 22
            username: metatron
            password: metatron_password
    query:
      loader: # Unlike in "ingestion", when downloading query results, it is used to transfer download file generated by engine to application
        remoteType: LOCAL
        localBaseDir: ${java.io.tmpdir:-/tmp}
```

Please let me know if the setup is not working.
