### ISSUE TITLE
Hive personal database improvement

### ISSUE THREAD

**Issue by YooYoungmo** [metatron-app/metatron-discovery#2821]
**Is your feature request related to a problem? Please describe.**
#320 이슈에서 추가된 워크벤치에서 개인 hive 데이터베이스 기능은 Hive 커넥션에 커스텀 프로퍼티에 부가 정보를 입력하여 사용하는 방식입니다.
![image](https://user-images.githubusercontent.com/16472109/68271561-41650f00-00a4-11ea-8a3a-7e97361c7b3a.png)
첫 번째 문제는 다른 커넥션에 같은 정보를 사용하고 싶은 경우 중복으로 입력해야 합니다.
두 번째 문제는 보안에 민감한 정보(password)가 평문으로 노출되고 있습니다.

**Describe the solution you'd like**
메타트론 커넥션 프로퍼티에 추가했던 정보를 메타트론 config 파일(application.yaml)로 옮기고 Hive 커넥션에 커스텀 프로퍼티에는 연결 키(datasource-name)만 입력하는 방식으로 개선하고자 합니다.

![image](https://user-images.githubusercontent.com/16472109/68271960-98b7af00-00a5-11ea-84c4-62ae721ceb6a.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by kyungtaak** [comment]
@YooYoungmo 제안해주시는 방식은 이해했습니다만, 너무 특정기능에 의존적인 기능셋으로 보입니다. 보안적인 문제가 있다면, 다른 커넥션 셋도 문제가 있을가능성이 있으니, 아래와같이 범용적으로 사용할수 있도록 구성하는게 어떨런지요? 예를 들면, 

```
polaris:
  connection:
    property-gruop:
      gruop1:
         native.......:
         metatron....:
```
으로 하고, connection 설정에 "metatron.property.group.name:group1" 으로하면 좋을것 같습니다.
검토 부탁드립니다.

**Comment by YooYoungmo** [comment]
@kyungtaak 아래 처럼 쓰면 되나요?
```yaml
polaris:
   connection:
      property-group:
        group1:
          hdfs-conf-path: /Users/yooyoungmo/bettercode/metatron-discovery/upstream-master/hdfs-conf
          admin-name: admin
          admin-password: 1111
          personal-database-prefix: private
        group2:
          hdfs-conf-path: /test2/hdfs-conf
          admin-name: admin
          admin-password: qwer
          personal-database-prefix: pv
```
![image](https://user-images.githubusercontent.com/16472109/68459364-84f87e00-0248-11ea-9f85-eeb4e2cd139f.png)
