### ISSUE TITLE
The open target of the lnb menu supports "new tab" and "frame" types.

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#3155]
**Is your feature request related to a problem? Please describe.**
Depending on the situation, the method of opening the lnb menu should support "new tab" instead of "frame".
So, it is optional to support both methods.

**Describe the solution you'd like**
Add openTarget attribute to submenu of lnb extension to branch.

application.yaml sample
```
  extensions:
    lnb:
      - name: Extensions
        parent: management
        level: 2
        subMenus:
          - name: Open New Tab menu
            parent: Extensions
            route: https://metatron.app
            openTarget: blank
          - name: Open in iFrame menu
            parent: Extensions
            route: https://metatron.app
            openTarget: frame
```

**Describe alternatives you've considered**

**Additional context**
